worker_processes auto;

events {
    worker_connections 4096;
    multi_accept on;
}

http {

    access_log off;
    error_log /var/log/nginx/error.log warn;

    upstream fastapi_cluster {
        server web_1:5000;
        server web_2:5000;
        server web_3:5000;
        keepalive 64;        # ← connexions persistantes vers Flask
    }

    server {
        listen 80;

        location / {
            proxy_pass http://fastapi_cluster;
            
            # Paramètres requis pour activer le Keepalive vers l'Upstream
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}