CREATE TABLE IF NOT EXISTS housing (
    BROKERTITLE VARCHAR(255),
    TYPE VARCHAR(100),
    PRICE NUMERIC,
    BEDS INTEGER,
    BATH NUMERIC,
    PROPERTYSQFT NUMERIC,
    ADDRESS TEXT,
    STATE VARCHAR(100),
    MAIN_ADDRESS TEXT,
    ADMINISTRATIVE_AREA_LEVEL_2 VARCHAR(255),
    LOCALITY VARCHAR(255),
    SUBLOCALITY VARCHAR(255),
    STREET_NAME VARCHAR(255),
    LONG_NAME TEXT,
    FORMATTED_ADDRESS TEXT,
    LATITUDE NUMERIC,
    LONGITUDE NUMERIC
);

COPY housing FROM '/housing.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE